import { StockFormulation, WorkOrder } from "./types";

function readings(pattern: ("compliant" | "critical" | "action_taken" | "pending")[], base: [number, number][]): WorkOrder["readings"] {
  return pattern.map((status, i) => ({
    day: i + 1,
    date: new Date(2026, 6, 12 + i).toISOString(),
    airspace: status === "pending" ? null : base[i][0],
    probeCase: status === "pending" ? null : base[i][1],
    ambientTemp: status === "pending" ? null : 24 + i * 0.4,
    productTemp: status === "pending" ? null : 27 - i * 0.2,
    humidity: status === "pending" ? null : 55 + i,
    status,
    correctiveAction:
      status === "action_taken"
        ? {
            note: "Additional fumigant dosing applied; re-sealed and re-checked. Levels restored above threshold.",
            loggedBy: "Grace Phiri",
            loggedAt: new Date(2026, 6, 14, 14, 10).toISOString(),
          }
        : undefined,
  }));
}

export const mockWorkOrders: WorkOrder[] = [
  {
    id: "wo-1",
    code: "SHP-192716",
    codeSource: "client_supplied",
    client: "Alliance One Tobacco Malawi Limited",
    cropType: "tobacco",
    scale: "industrial",
    status: "certified",
    createdAt: "2026-07-10T08:00:00Z",
    salesOrderNo: "N/A",
    shipmentNo: "192716",
    deliveryNo: "80855003",
    si: {
      tobaccoSupplier: "Alliance One Tobacco Malawi Limited, on behalf of Alliance One International LLC",
      supplierAddress: "P.O. Box 30522, Lilongwe 3, Malawi.",
      consignee: "C Steinweg Bridge Pty Ltd",
      consigneeAddress: "P.O. Box 5948, Durban 4000, South Africa.",
      cropYear: "2025 Crop",
      tobaccoType: "Flue Cured Tobacco / Zambia",
      netWeight: "126,000 KGS",
      quantity: "630 Cartons",
      polylined: "Yes",
      gradeName: "ZL1OFTHN",
      caseNos: "653-1282",
      countryOfOrigin: "Zambia",
      location: "Primon Warehouse, Lilongwe",
      warehouseSection: "Bay 4",
      complete: true,
    },
    fumigation: {
      fumigationType: "sheeted_stack",
      fumigantName: "Aluminium Phosphide",
      formulation: "Plate (33g)",
      dose: 1.5,
      totalVolume: 448,
      totalFumigantUsed: 672,
      complete: true,
    },
    readings: readings(
      ["compliant", "compliant", "action_taken", "compliant", "compliant", "compliant"],
      [
        [1000, 984],
        [914, 819],
        [512, 497],
        [701, 647],
        [791, 704],
        [745, 695],
      ]
    ),
    datePlaced: "2026-07-12T09:00:00Z",
    aerationBegan: "2026-07-19T08:00:00Z",
    aerationCompleted: "2026-07-21T08:00:00Z",
    durationHours: 168,
    certificateNumber: "FCC-2026-000512",
    certifiedAt: "2026-07-21T16:05:00Z",
  },
  {
    id: "wo-2",
    code: "WO-2026-00118",
    codeSource: "auto_generated",
    client: "Kasungu Flue-Cured Growers Cooperative",
    cropType: "tobacco",
    scale: "smallholder",
    status: "flagged",
    createdAt: "2026-08-20T08:00:00Z",
    si: {
      tobaccoSupplier: "Kasungu Flue-Cured Growers Cooperative",
      supplierAddress: "P.O. Box 88, Kasungu, Malawi.",
      consignee: "Limbe Leaf Tobacco Company",
      consigneeAddress: "P.O. Box 60, Blantyre, Malawi.",
      cropYear: "2026 Crop",
      tobaccoType: "Flue Cured Tobacco",
      netWeight: "18,400 KGS",
      quantity: "92 Bales",
      polylined: "No",
      gradeName: "L2O",
      caseNos: "004-096",
      countryOfOrigin: "Malawi",
      location: "Kasungu Depot",
      warehouseSection: "Section C",
      complete: false,
    },
    fumigation: {
      fumigationType: "container",
      fumigantName: "Aluminium Phosphide",
      formulation: "Sachet (11g)",
      dose: 2.0,
      totalVolume: 96,
      totalFumigantUsed: 192,
      complete: true,
    },
    readings: readings(
      ["compliant", "critical", "pending", "pending", "pending", "pending"],
      [
        [880, 845],
        [540, 511],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
      ]
    ),
    datePlaced: "2026-08-24T10:30:00Z",
  },
  {
    id: "wo-3",
    code: "WO-2026-00121",
    codeSource: "auto_generated",
    client: "Central Grain Millers Ltd",
    cropType: "grain",
    scale: "industrial",
    status: "in_progress",
    createdAt: "2026-08-25T08:00:00Z",
    si: {
      tobaccoSupplier: "Central Grain Millers Ltd",
      supplierAddress: "Area 9, Lilongwe, Malawi.",
      consignee: "Central Grain Millers Ltd",
      consigneeAddress: "Area 9, Lilongwe, Malawi.",
      cropYear: "2026",
      tobaccoType: "Maize",
      netWeight: "240,000 KGS",
      quantity: "4,800 Bags",
      polylined: "No",
      gradeName: "Grade 1",
      caseNos: "N/A",
      countryOfOrigin: "Malawi",
      location: "CGM Warehouse, Lilongwe",
      warehouseSection: "Silo 2",
      complete: true,
    },
    fumigation: {
      fumigationType: "sheeted_stack",
      fumigantName: "Aluminium Phosphide",
      formulation: "Tablet (1g)",
      dose: 1.8,
      totalVolume: 820,
      totalFumigantUsed: 1476,
      complete: true,
    },
    readings: readings(
      ["compliant", "compliant", "compliant", "pending", "pending", "pending"],
      [
        [960, 932],
        [880, 861],
        [812, 790],
        [0, 0],
        [0, 0],
        [0, 0],
      ]
    ),
    datePlaced: "2026-08-27T07:45:00Z",
  },
  {
    id: "wo-4",
    code: "WO-2026-00109",
    codeSource: "auto_generated",
    client: "Namitete Household — J. Banda",
    cropType: "tobacco",
    scale: "smallholder",
    status: "draft",
    createdAt: "2026-08-28T08:00:00Z",
    si: {
      tobaccoSupplier: "",
      supplierAddress: "",
      consignee: "",
      consigneeAddress: "",
      cropYear: "",
      tobaccoType: "",
      netWeight: "",
      quantity: "",
      polylined: "No",
      gradeName: "",
      caseNos: "",
      countryOfOrigin: "Malawi",
      location: "",
      warehouseSection: "",
      complete: false,
    },
    fumigation: {
      fumigationType: "container",
      fumigantName: "Aluminium Phosphide",
      formulation: "",
      dose: 0,
      totalVolume: 0,
      totalFumigantUsed: 0,
      complete: false,
    },
    readings: [],
  },
  {
    id: "wo-5",
    code: "SHP-192901",
    codeSource: "client_supplied",
    client: "Alliance One Tobacco Malawi Limited",
    cropType: "tobacco",
    scale: "industrial",
    status: "under_review",
    createdAt: "2026-08-15T08:00:00Z",
    salesOrderNo: "N/A",
    shipmentNo: "192901",
    deliveryNo: "80856110",
    si: {
      tobaccoSupplier: "Alliance One Tobacco Malawi Limited",
      supplierAddress: "P.O. Box 30522, Lilongwe 3, Malawi.",
      consignee: "Universal Leaf Tobacco Company",
      consigneeAddress: "P.O. Box 25099, Richmond, VA, USA.",
      cropYear: "2025 Crop",
      tobaccoType: "Flue Cured Tobacco / Malawi",
      netWeight: "88,000 KGS",
      quantity: "440 Cartons",
      polylined: "Yes",
      gradeName: "ML1OFTHN",
      caseNos: "112-552",
      countryOfOrigin: "Malawi",
      location: "Primon Warehouse, Lilongwe",
      warehouseSection: "Bay 2",
      complete: true,
    },
    fumigation: {
      fumigationType: "sheeted_stack",
      fumigantName: "Magnesium Phosphide",
      formulation: "Plate (33g)",
      dose: 1.5,
      totalVolume: 312,
      totalFumigantUsed: 468,
      complete: true,
    },
    readings: readings(
      ["compliant", "compliant", "compliant", "compliant", "compliant", "compliant"],
      [
        [944, 918],
        [890, 855],
        [833, 802],
        [790, 761],
        [744, 719],
        [712, 688],
      ]
    ),
    datePlaced: "2026-08-17T09:15:00Z",
    aerationBegan: "2026-08-24T08:00:00Z",
    aerationCompleted: "2026-08-26T08:00:00Z",
    durationHours: 168,
  },
];

export const mockStock: StockFormulation[] = [
  {
    id: "stk-1",
    fumigant: "Aluminium Phosphide",
    formulation: "Sachet (11g)",
    cropType: "tobacco",
    unit: "units",
    quantityOnHand: 340,
    lowStockThreshold: 100,
  },
  {
    id: "stk-2",
    fumigant: "Aluminium Phosphide",
    formulation: "Tablet (1g)",
    cropType: "grain",
    unit: "units",
    quantityOnHand: 62,
    lowStockThreshold: 150,
  },
  {
    id: "stk-3",
    fumigant: "Magnesium Phosphide",
    formulation: "Plate (33g)",
    cropType: "both",
    unit: "units",
    quantityOnHand: 218,
    lowStockThreshold: 80,
  },
];

export const mockPendingSubmissions = [
  {
    id: "sub-1",
    sourceType: "rfw" as const,
    name: "Chikondi Banda",
    contact: "chikondi.banda@example.com · 0991 234 567",
    cropOrService: "Household pest control — rodents",
    message: "Rodent activity in the roof space, Area 47, Lilongwe. Requesting a quote and earliest visit.",
    receivedAt: "2026-08-30T09:12:00Z",
  },
  {
    id: "sub-2",
    sourceType: "work_order" as const,
    name: "Mzuzu Grain Cooperative",
    contact: "info@mzuzugrain.mw · 0888 654 321",
    cropOrService: "Maize — approx. 12,000kg",
    message: "New harvest ready for warehouse fumigation before onward transport.",
    receivedAt: "2026-08-29T14:40:00Z",
  },
  {
    id: "sub-3",
    sourceType: "rfq" as const,
    name: "Blessings Phiri",
    contact: "b.phiri@example.com · 0995 111 222",
    cropOrService: "Termite treatment — residential",
    message: "Noticed termite mud tubes along the foundation. Would like an inspection quote.",
    receivedAt: "2026-08-28T11:05:00Z",
  },
];

